# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKFh6VKGZiGqgx5kx86M2rubwyEjqbw9

**Лаборатрная работа 2**
Данные "Изменение стоимости акций"
"""

import numpy as np
import pandas as pd
import os
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sns

os.makedirs("train", exist_ok=True)
os.makedirs("test", exist_ok=True)

np.random.seed(55)

def generate_date(days, start_buy=100, volatility=0.02, trend=0.05, namee="", anomaly=0.02):
  time = np.arange(days)

  returns = np.random.normal(trend, volatility, days)
  price = start_buy * np.exp(np.cumsum(returns))

  quarterly_effect = 5 * np.sin(2 * np.pi * time / 63)
  price = price + quarterly_effect

  noise = np.random.normal(0, start_buy * 0.01, days)
  fin_nois = price + noise

  start_date = datetime(2020, 1, 1)
  dates = [start_date + timedelta(days=i) for i in range(days)]

  df = pd.DataFrame({
        'date': dates,
        'close': fin_nois,
        'company': namee,
     })
  return df

df_train1 = generate_date(
    days=504,
    start_buy=120,
    volatility=0.02,
    trend=0.0003,
    namee="bubl"
)
df_train1.to_csv("train/bubl_train.csv", index=False)

df_train2 = generate_date(
    days=504,
    start_buy=100,
    volatility=0.04,
    trend=0.0008,
    namee="habl"
)
df_train2.to_csv("train/habl_train.csv", index=False)

df_train3 = generate_date(
    days=504,
    start_buy=130,
    volatility=0.01,
    trend=0.0005,
    namee="madly"
)
df_train3.to_csv("train/madly_train.csv", index=False)

df_test1 = generate_date(
    days=63,
    start_buy=120,
    volatility=0.02,
    trend=0.0003,
    namee="bubl"
)
df_test1.to_csv("test/bubl_test.csv", index=False)

df_test2 = generate_date(
    days=63,
    start_buy=100,
    volatility=0.04,
    trend=0.0008,
    namee="habl"
)
df_test2.to_csv("test/habl_test.csv", index=False)

df_test3 = generate_date(
    days=63,
    start_buy=130,
    volatility=0.01,
    trend=0.0005,
    namee="madly"
)
df_test3.to_csv("test/madly_test.csv", index=False)